<?php
return array (
  'cfg_basehost' => 'http://iat.net.cn',
  'cfg_indexurl' => '',
  'cfg_indexname' => '学生科研项目管理平台',
  'cfg_webname' => '学生科研项目管理平台',
  'cfg_powerby' => 'Copyright © 2014 Powered by <a href="http://iat.net.cn" target="_blank">iat</a>. All Rights Reserved',
  'cfg_keywords' => '科研项目管理平台',
  'cfg_description' => '计算机科学与技术学院科研项目管理平台',
  'cfg_beian' => '',
  'cfg_cmspath' => '/EaglePHP',
  'cfg_cookie_encode' => 'dfergfddf454seddd',
  'cfg_backup_dir' => 'Backup',
  'cfg_adminemail' => 'iat.net.cn@gmail.com',
  'cfg_domain_cookie' => '/',
  'cfg_eag_log' => '1',
  'cfg_ftp_host' => 'localhost',
  'cfg_ftp_port' => '21',
  'cfg_ftp_user' => 'maojian',
  'cfg_ftp_pwd' => '123456',
  'cfg_ftp_root' => '/',
  'cfg_ftp_mkdir' => '1',
  'cfg_sendmail_bysmtp' => '1',
  'cfg_smtp_server' => 'smtp.163.com',
  'cfg_smtp_port' => '25',
  'cfg_smtp_usermail' => 'iatboy@163.com',
  'cfg_smtp_user' => 'iatboy@163.com',
  'cfg_smtp_password' => 'ysl88842412',
  'cfg_admin_sysname' => '学生科研项目管理平台',
  'cfg_admin_sysdesc' => '“科研项目管理平台”是为方便管理科研项目而开发的平台，在同一平台的基础上，项目主持人、辅导员、学院管理员以及学校管理员可以方便的查看、统计、管理科研项目。',
  'cfg_sys_version' => 'v 2.0',
  'cfg_access_log' => '1',
  'cfg_system_log' => '1',
  'cfg_debug_mode' => '1',
  'cfg_mysql_type' => 'mysql',
  'cfg_orm_dir' => 'Field',
  'cfg_session_dir' => 'Session',
  'cfg_img_width' => '300',
  'cfg_img_height' => '300',
  'cfg_original_imgdir' => 'photo/original/',
  'cfg_middle_imgdir' => 'photo/middle/',
  'cfg_thumbnail_imgdir' => 'photo/thumbnail/',
  'cfg_memcache_host' => '127.0.0.1',
  'cfg_memcache_port' => '11211',
  'cfg_auot_description' => '100',
  'cfg_rm_remote' => '0',
  'cfg_arc_dellink' => '1',
  'cfg_arc_autopic' => '0',
  'cfg_arc_autokeyword' => '1',
  'cfg_title_maxlen' => '60',
  'cfg_check_title' => '1',
  'cfg_upload_switch' => '1',
  'cfg_html_dir' => '/a',
  'cfg_html_make' => '0',
  'cfg_adv_dir' => 'adv/',
  'cfg_filter_word' => '非典|艾滋病|阳痿|她妈|它妈|他妈|你妈|去死|贱人',
  'cfg_cache_dir' => 'File',
  'cfg_cache_type' => 'File',
  'cfg_cache_time' => '10',
  'cfg_login_email' => '0',
  'cfg_debug_email' => '0',
  'cfg_case_dir' => 'case/',
  'cfg_video_dir' => 'video/',
  'cfg_taobao_isopen' => '0',
  'cfg_taobao_appkey' => '21072832',
  'cfg_taobao_secret' => '6885676831c4b9837090c03b26c85819',
  'cfg_taobao_callback' => '',
  'cfg_taobao_pid' => '32251410',
  'cfg_refresh_time' => '9',
  'cfg_redis_host' => '127.0.0.1',
  'cfg_redis_port' => '6379',
  'cfg_ping_sites' => 'http://ping.baidu.com/ping/RPC2
http://blogsearch.google.com/ping/RPC2
http://blog.youdao.com/ping/RPC2
http://rpc.pingomatic.com/
http://www.feedsky.com/api/RPC2
http://xianguo.com/xmlrpc/ping.php
http://www.bloglines.com/ping',
  'cfg_open_rewrite' => '0',
  'cfg_links_dir' => 'links/',
  'cfg_open_weather' => '0',
  'cfg_open_cache' => '1',
  'qq_appid' => '100369006',
  'qq_appkey' => 'e31f9797dd40c1e2259ef1cc317f19c9',
  'sina_client_id' => '2822752406',
  'sina_client_secret' => '4873666fd3c395a6194f445977528c7b',
  'cfg_project_dir' => 'project/',
  'cfg_template_dir' => 'template/',
  'KYJJ_begin_add_time' => '2014-01-28',
  'KYJJ_end_add_time' => '2014-04-26',
  'KYJJ_begin_middle_check_time' => '2014-04-02',
  'KYJJ_end_middle_check_time' => '2014-04-28',
  'KYJJ_begin_final_check_time' => '2014-04-02',
  'KYJJ_end_final_check_time' => '2014-10-08',
  'cfg_KYJJ_dir' => 'project/KYJJ/',
  'JZJJ_begin_add_time' => '2014-03-08',
  'JZJJ_end_add_time' => '2014-03-21',
  'cfg_JZJJ_dir' => 'project/JZJJ/',
  'cfg_awards_dir' => 'awards/',
);
?>